version: '3.2'

services:
  temperature:
    build: ./co2logger
    image: co2logger
    volumes:
      - type: volume
        source: nas
        target: "/data"
      - type: bind
        source: "./co2logger"
        target: "/app"
    privileged: true
    environment:
      TZ: Asia/Tokyo
      PYTHONUNBUFFERED: 1
    working_dir: /app
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/gpiomem:/dev/gpiomem"
    command: python log_tmp.py --dbpath /data/dht20
  
  display:
    build: ./co2logger
    image: co2logger
    volumes:
      - type: volume
        source: nas
        target: "/data"
      - type: bind
        source: "./co2logger"
        target: "/app"
    privileged: true
    environment:
      TZ: Asia/Tokyo
      PYTHONUNBUFFERED: 1
    working_dir: /app
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/gpiomem:/dev/gpiomem"
    command: python display_co2.py --interval_sec 20 --dbpath /data/co2.latest --fp_csv /data/dht20

  
  co2:
    build: ./co2logger
    image: co2logger
    volumes:
      # - type: bind
      #   source: "./db"
      #   target: "/db"
      - type: volume
        source: nas
        target: "/db"
      - type: bind
        source: "./co2logger"
        target: "/app"
    environment:
      TZ: Asia/Tokyo
    working_dir: /app
    devices:
      - "/dev/ttyS0:/dev/ttyS0"
    command: python log_co2.py --interval 60 --logpath /db/co2.log --out /db/co2.latest
    

  
  
  # web:
  #   build: ./web
  #   image: co2web
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - type: bind
  #       source: "./web"
  #       target: "/web"
  #   working_dir: /web

volumes:
  nas:
    name: nas-co2
    external: true
