version: '3.2'

services:
  co2plot:
    command: python plot_co2.py --interval 10 --dbpath /db/co2_debug.db --outpath /image/result.png

  co2log:
    volumes:
      - type: bind
        source: "."
        target: "/app"
    working_dir: /app/co2logger
    devices:
      - "/dev/ttyS0:/dev/ttyS0"
    command: python log_co2.py --debug --interval 5 --dbpath /db/co2_debug.db
