version: '3'

services:
  co2plot:
    build: ./co2log
    image: co2logger
    volumes:
      - ./db:/db
    environment:
      TZ: Asia/Tokyo
    working_dir: /app
    command: python plot_co2.py --dbpath /db/co2.db --outpath /db/restult.png

  co2log:
    build: ./co2log
    image: co2logger
    volumes:
      - ./db:/db
      - image:/image
    environment:
      TZ: Asia/Tokyo
    working_dir: /app
    command: python log_co2.py --debug --dbpath /db/co2.db
volumes:
  image: